"use strict";
const V2Supabase=window.supabase.createClient(SupabaseUrl,SupabasePublishableKey);
function T(k,f){const v=window.SunriseI18nReady?SunriseT(k):k;return v===k?f:v}
function TaiwanNow(){return new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Taipei"}))}
function DutyWeekStart(d){const x=new Date(d);const day=x.getDay();const diff=day===0?-6:1-day;x.setDate(x.getDate()+diff);x.setHours(10,0,0,0);if(d<x)x.setDate(x.getDate()-7);return x}
function DateKey(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
async function LoadDuty(){const start=DateKey(DutyWeekStart(TaiwanNow()));let o=await V2Supabase.from("duty_week_overrides").select("member_ids").eq("week_start",start).maybeSingle();let ids=o.data&&o.data.member_ids;if(!ids){let s=await V2Supabase.from("duty_settings").select("rotation_groups,anchor_week").eq("id",1).maybeSingle();if(s.data&&s.data.rotation_groups&&s.data.rotation_groups.length){const anchor=new Date(s.data.anchor_week+"T10:00:00");const weeks=Math.floor((DutyWeekStart(TaiwanNow())-anchor)/604800000);const groups=s.data.rotation_groups;ids=groups[((weeks%groups.length)+groups.length)%groups.length]}}if(!ids||!ids.length){document.getElementById("dutyList").textContent=T("sunV2.noDuty","暫無設定");return}const m=await V2Supabase.from("members").select("id,game_name").in("id",ids);const map=new Map((m.data||[]).map(x=>[String(x.id),x.game_name]));document.getElementById("dutyList").textContent=ids.map(x=>map.get(String(x))).filter(Boolean).join(" 、 ")||T("sunV2.noDuty","暫無設定")}
async function LoadTrain(){const now=TaiwanNow();let logic=new Date(now);if(now.getHours()<10)logic.setDate(logic.getDate()-1);const idx=logic.getDay()===0?6:logic.getDay()-1;try{const r=await fetch("train.txt?t="+Date.now());const lines=(await r.text()).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);document.getElementById("trainDriver").textContent=lines[idx]||lines[0]||"-"}catch(e){document.getElementById("trainDriver").textContent="-"}}
function EventFor(d){const base=new Date("2026-04-06T10:00:00");const days=Math.floor((d-base)/86400000);const week=Math.floor(days/7);const dow=((d.getDay()+6)%7);if(dow===2)return week%2===0?"zombie":"vanguard";if(dow===4)return week%2===0?"boss":"doomsday";return "none"}
function Build(){const now=TaiwanNow(), zone=document.getElementById("zone"),strategy=document.getElementById("strategy");zone.innerHTML="";strategy.innerHTML="";for(let i=0;i<7;i++){const d=new Date(now);d.setDate(now.getDate()+i);const dow=d.getDay();const r=document.createElement("div");r.className="row"+(i===0?" today":"");const red=dow===1||dow===2||dow===3;const truck=dow===4||dow===5||dow===6?"UR":"SSR → UR";const ev=EventFor(d);r.innerHTML="<b>"+d.toLocaleDateString(i18next.language,{timeZone:"Asia/Taipei",weekday:"short",month:"2-digit",day:"2-digit"})+"</b> · <span class='"+(red?"red":"green")+"'>"+(red?"🔴 Red Star":"No Red Star")+"</span> · 🚚 <span class='"+(truck==="UR"?"gold":"purple")+"'>"+truck+"</span>"+(ev!=="none"?" · <span class='event'>"+ev+"</span>":"");strategy.appendChild(r)}zone.innerHTML=strategy.firstElementChild?strategy.firstElementChild.innerHTML:""}
document.addEventListener("DOMContentLoaded",async()=>{await LoadDuty();await LoadTrain();Build()});document.addEventListener("sunriseLanguageChanged",Build);