"use strict";
const V2Supabase=window.supabase.createClient(SupabaseUrl,SupabasePublishableKey);
function Lang(){return (window.i18next&&i18next.language)||"zh-TW"}
const Txt={ "zh-TW":{period:"時段",zone:"戰區",red:"🔴 紅星",yes:"有任務",no:"無任務",today:"建議派出(當日的)",saved:"建議派出(先前保留的)",save:"建議保留",truck:"🚚 貨車",ur:"限 UR",ssr:"優先 SSR 再 UR",event:"✨ 事件",zombie:"🧟 殭屍入侵",boss:"👹 狂暴首領(國會周圍)",vanguard:"👨‍🏫 先鋒教官",doomsday:"🌋 末日降臨(打3隻阿胖)",none:"無特殊大型活動",drill:"⚔️ 聯盟軍演",note:"📝 備註",exp:"需要打完遠征",shop:"購買商店物品",radar:"存雷達",mine:"晚上挖礦到隔天10點(不能離開礦點)",on:"護盾 ON (GMT+8 10:00)",off:"護盾 OFF (GMT+8 10:00)",noDuty:"暫無設定"},
en:{period:"Period",zone:"Zones",red:"🔴 Red Star",yes:"Available",no:"None",today:"Dispatch (Today)",saved:"Dispatch (Saved)",save:"SAVE",truck:"🚚 Truck",ur:"UR only",ssr:"SSR first, then UR",event:"✨ Event",zombie:"🧟 Zombie Invasion",boss:"👹 Rampage Boss",vanguard:"👨‍🏫 Vanguard",doomsday:"🌋 Doomsday",none:"No major event",drill:"⚔️ Drill",note:"📝 Note",exp:"Complete Campaign",shop:"Purchase Shop Items",radar:"Save Radar tasks",mine:"Mine overnight until 10 AM",on:"Shield ON (10:00 AM)",off:"Shield OFF (10:00 AM)",noDuty:"Not configured"},
vi:{period:"Thời gian",zone:"Chiến khu",red:"🔴 Sao Đỏ",yes:"Có nhiệm vụ",no:"Không có",today:"Gửi đi (Hôm nay)",saved:"Gửi đi (Đã lưu)",save:"LƯU LẠI",truck:"🚚 Xe tải",ur:"Chỉ UR",ssr:"Ưu tiên SSR -> UR",event:"✨ Sự kiện",zombie:"🧟 Thây ma xâm chiếm",boss:"👹 Boss cuồng bạo",vanguard:"👨‍🏫 Huấn luyện viên",doomsday:"🌋 Ngày tận thế",none:"Không có sự kiện",drill:"⚔️ Diễn tập liên minh",note:"📝 Ghi chú",exp:"Hoàn thành Viễn chinh",shop:"Mua đồ trong Shop",radar:"Lưu nhiệm vụ Radar",mine:"Đào mỏ qua đêm",on:"Bật Khiên (09:00 AM ICT)",off:"Tắt Khiên (09:00 AM ICT)",noDuty:"Chưa thiết lập"}};
function T(){return Txt[Lang()]||Txt.en}
function TaiwanNow(){const n=new Date(),u=n.getTime()+n.getTimezoneOffset()*60000;return new Date(u+8*3600000)}
function LogicZero(){const n=TaiwanNow(),d=new Date(n);if(n.getHours()<10)d.setDate(d.getDate()-1);return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function DutyWeekStart(d){const x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));x.setHours(10,0,0,0);if(d<x)x.setDate(x.getDate()-7);return x}
function DateKey(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
async function LoadDuty(){const start=DateKey(DutyWeekStart(TaiwanNow()));const o=await V2Supabase.from("duty_week_overrides").select("member_ids").eq("week_start",start).maybeSingle();let ids=o.data&&o.data.member_ids;if(!ids){const s=await V2Supabase.from("duty_settings").select("rotation_groups,anchor_week").eq("id",1).maybeSingle();if(s.data&&s.data.rotation_groups&&s.data.rotation_groups.length){const a=new Date(s.data.anchor_week+"T10:00:00"),w=Math.floor((DutyWeekStart(TaiwanNow())-a)/604800000),g=s.data.rotation_groups;ids=g[((w%g.length)+g.length)%g.length]}}if(!ids||!ids.length){document.getElementById("dutyList").textContent=T().noDuty;return}const m=await V2Supabase.from("members").select("id,game_name").in("id",ids),map=new Map((m.data||[]).map(x=>[String(x.id),x.game_name]));document.getElementById("dutyList").textContent=ids.map(x=>map.get(String(x))).filter(Boolean).join(" 、 ")||T().noDuty}
async function LoadTrain(){const n=TaiwanNow(),d=new Date(n);if(n.getHours()<10)d.setDate(d.getDate()-1);const idx=d.getDay()===0?6:d.getDay()-1;try{const r=await fetch("train.txt?t="+Date.now()),a=(await r.text()).split(/\r?\n/).map(x=>x.trim()).filter(Boolean);document.getElementById("trainDriver").textContent=a[idx]||a[0]||"-"}catch(e){document.getElementById("trainDriver").textContent="-"}}
function Render(){const t=T(),z=LogicZero(),zones=[["1769","1772","1775","1776","1783","1789","1790","1793","1796"],["1765","1770","1771","1777","1778","1779","1784","1785","1791","1797"],["1766","1767","1768","1773","1774","1780","1781","1782","1786","1787","1788","1792","1794","1795"]],base=new Date(2026,2,20);let zi=Math.floor((z-base)/86400000)%3;if(zi<0)zi+=3;const h=Lang()==="vi"?9:10,end=new Date(z.getTime()+86400000);document.getElementById("zone").innerHTML="<strong>"+t.period+"：</strong>"+(z.getMonth()+1)+"/"+z.getDate()+" "+h+":00 AM ~ "+(end.getMonth()+1)+"/"+end.getDate()+" "+h+":00 AM "+(Lang()==="vi"?"(GMT+7)":"(GMT+8)")+"<br><strong>"+t.zone+"：</strong>"+zones[zi].join(", ");let out="";for(let i=0;i<7;i++){const d=new Date(z.getTime()+i*86400000),dow=d.getDay(),hasRed=Math.floor((d-new Date(2026,2,24))/86400000)%3===0,special=dow===2||dow===6,weekOne=Math.floor((d-new Date(2026,3,6))/(7*86400000))%2===0,drill=Math.floor((d-new Date(2026,3,6))/86400000)%2!==0;let rc=hasRed?"<span class='red'>"+t.yes+"</span> / ":t.no;if(hasRed){if(special)rc+="<span class='green'>"+t.today+"</span>";else{let save=false;for(let j=1;j<=2;j++)if(new Date(d.getTime()+j*86400000).getDay()%4===2)save=true;rc+=save?"<span class='red'>"+t.save+"</span>":"<span class='green'>"+t.today+"</span>"}}else if(special)rc+=" / <span class='green'>"+t.saved+"</span>";let ev="";if(weekOne){if(dow>=3&&dow<=5)ev=t.zombie;else if(dow===0)ev=t.boss}else{if(dow>=3&&dow<=5)ev=t.vanguard;else if(dow===0)ev=t.doomsday}ev=ev||t.none;if(drill)ev+=" / "+t.drill;const notes=[];if([1,3,5].includes(dow))notes.push(t.exp);if(dow===0)notes.push(t.shop);if([0,2,4].includes(dow))notes.push(t.radar);if(dow===0)notes.push(t.mine);let row="<strong>"+d.toLocaleDateString(Lang(),{month:"2-digit",day:"2-digit",weekday:"long"})+"</strong><br>└ "+t.red+"："+rc+"<br>└ "+t.truck+"：<span class='"+(special?"gold":"purple")+"'>"+(special?t.ur:t.ssr)+"</span><br>└ "+t.event+"：<span class='event'>"+ev+"</span>"+(notes.length?"<br>└ "+t.note+"："+notes.join(" / "):"");if(dow===6)row+="<br>└ 🛡️ <span class='red'>"+t.on+"</span>";else if(dow===0)row+="<br>└ 🛡️ <span class='red'>"+t.off+"</span>";out+=(i===0?"<div class='row today'>":"<div class='row'>")+row+"</div>"+(i<6?"<hr>":"")}document.getElementById("strategy").innerHTML=out}}
document.addEventListener("DOMContentLoaded",async()=>{await LoadDuty();await LoadTrain();Render()});document.addEventListener("sunriseLanguageChanged",()=>{LoadDuty();Render()});